### ISSUE TITLE
"The Atlantic" style outquotes in articles

### ISSUE THREAD

**Issue by jsonkao** [stuyspec/stuyspec.com#100]
Every article has the property `outquotes`, an array of outquotes. It'd be nice if outquotes were used in article content like in _The Atlantic_.

## Implementation
Following the [contributing guidelines](https://github.com/stuyspec/client-app/blob/develop/CONTRIBUTING.md), make your way to the `ArticleBody.js` component. The actual paragraphs in an article are in the `dangerouslySetInnerHTML`, and you'll need to process that `content` to insert an outquote somewhere. Feel free to use the HTML tag `<outquote>...</outquote>` so you can easily style it.

## Design
![image](https://user-images.githubusercontent.com/15334952/35778170-874689e6-0988-11e8-84e6-4e44c70dda30.png)

**Comment by DJankauskas** [comment]
Outquotes aren't supported in the CMS, and while they can be added, I don't think they're particularly useful.
