### ISSUE TITLE
default proptypes for article summary components

### ISSUE THREAD

**Issue by jsonkao** [stuyspec/stuyspec.com#101]
Each article summary component with props should have `propTypes` and `defaultProps` if sensible. Take a look at React's [typechecking documentation](https://reactjs.org/docs/typechecking-with-proptypes.html) for more info.

If attempting this issue, be sure to follow our [contributing guidelines](https://github.com/stuyspec/client-app/blob/develop/CONTRIBUTING.md).

**Comment by DJankauskas** [comment]
The codebase is using Typescript now, so proptypes isn't needed anymore. The summary components aren't typed, so I would change this issue to do that, but since we're going to rewrite the homepage medium-term I'll be closing this. New components will of course be typed.
