### ISSUE TITLE
Data fetch fail is not caught

### ISSUE THREAD

**Issue by NicholasLYang** [stuyspec/stuyspec.com#155]
When the page fails to fetch the data from the API, the failure isn't caught and the user isn't redirected to the data error page. This is not acceptable, as it leaves the user with a blank white page, which is very confusing. Basically just catch the apollo fetch error:

```
Unhandled error Network error: NetworkError when attempting to fetch resource. ApolloError@http://localhost:3002/build.js line 56 > Function line 3 > eval:77:21
``

**Comment by angeredgecko** [comment]
hi

**Comment by DJankauskas** [comment]
Using [error boundaries](https://reactjs.org/docs/error-boundaries.html) is a good idea. You might want to look into using the existing [DataErrorPage](https://github.com/stuyspec/stuyspec.com/blob/develop/src/js/modules/core/components/DataErrorPage.js).

**Comment by DJankauskas** [comment]
Fixed behavior for articles. However, still todo for total failure to fetch vital homescreen or sidebar content.
