### ISSUE TITLE
Incomplete replacement of Gulp for Webpack

### ISSUE THREAD

**Issue by pierreTklein** [stuyspec/stuyspec.com#180]
Hey y'all! 
Proud stuy alum here (grad '15). I was trying to navigate to www.stuyspec.com, and noticed that the webpage isn't loading (`ERR_CONNECTION_TIMED_OUT`). I wasn't sure whether you were aware, so I'm making this issue to let you know.

**Comment by pierreTklein** [comment]
I was able to access your site, but saw that there might be an additional issue, stemming from here https://github.com/stuyspec/stuyspec.com/blob/a62dce40a171cd7d04825db9b4cc1c909ac50acb/src/constants.js#L2.
![image](https://user-images.githubusercontent.com/17463268/52538497-5f822680-2d41-11e9-9565-fc9a221ab6b0.png)

**Comment by DJankauskas** [comment]
Thank you so much for filing this issue! The site was undergoing deployment, but unfortunately the code was flawed in several ways, one of them being an incomplete replacement of Gulp for Webpack which you found. I temporarily reverted changes and the site now works, but I'll leave this issue open until the Gulp issue is fixed. Again, thank you!

**Comment by pierreTklein** [comment]
No worries! You guys are doing great work 🚀.
