### ISSUE TITLE
Bug Fixes + Enhancements

### ISSUE THREAD

**Issue by vs2961** [stuyspec/stuyspec.com#235]
- [x] Subscribe panel is shifted to the left
- [x] Time bugs - Just something I noticed recently, the hour seems to be off when articles are uploaded. May have to do with the system time on a person's computer.
- [ ] Be able to search for users, in addition to articles
- [x] Fix Circle CI

**Comment by vs2961** [comment]
More Subscribe Panel details can be found in #95

**Comment by abir-taheer** [comment]
I know that the CI failed for my commit, but that's as a result of runtime warnings being treated as errors during CI and the stuyspec.com app has a lot of runtime warnings.  Most of them are easy fixes. I made an issue [here](https://github.com/stuyspec/stuyspec.com/issues/250).
