### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by vs2961** [stuyspec/stuyspec.com#252]
There is currently a bug where all the sections don't show up on the bottom on a phone. 
![image](https://user-images.githubusercontent.com/33765960/79381314-cd227780-7f2f-11ea-9b03-5d5850f4f820.png)

**Comment by AndySok** [comment]
okay that should be fairly easy to fix, for some reason the div's 7th child onwards has a `display: none;` tag by default. Turning it off made all of the sections show up
![image](https://user-images.githubusercontent.com/19246179/84848415-17ec6880-b021-11ea-9d9a-e141daeadc82.png)
I believe the reason behind it being hidden is that back in 2018 the 7th child was the "About Us" section and this tag was made as sort of a fix for the section showing up twice? idk really
