### ISSUE TITLE
Create a new /developers page for past web editors

### ISSUE THREAD

**Issue by vs2961** [stuyspec/stuyspec.com#290]
All the way at the bottom, there are credits to past people who have worked on the website. We've decided that this should no longer be there, as history is documented on Github anyways.

**Comment by DJankauskas** [comment]
Hey, I get that you probably don't want a list of past contributors accumulating in the footer endlessly, and it's a fair question as to who actually deserves to be on it in the first place, but at least some of those contributors have done a ton of really great work that deserves to be remembered (past the obscurity of GitHub where few will check). Why not instead link to a dedicated page with a list of all the major-ish contributors? Writers and artists get their own individual pages, so the least the programmers could get is a shared page. Maybe at `/programmers' or '/developers'?

**Comment by AndySok** [comment]
I suppose that is something to consider! I might take a look into implementing a dedicated page later this weekend

**Comment by vs2961** [comment]
Great idea! I was just thinking exactly what you mentioned, that names were just going to stack up at the bottom of the page. I've changed the issue to creating a page for us instead.

**Comment by vs2961** [comment]
Done in #294 and #295
