### ISSUE TITLE
Side scrolling on iPhone 11/12 (possibly more)

### ISSUE THREAD

**Issue by pserb** [stuyspec/stuyspec.com#348]
Issue most likely stems from advertisement images not scaling properly on mobile which creates some overflow and side scrolling. This makes scrolling up and down the webpage really annoying as it's very easy to accidentally scroll side to side.

https://user-images.githubusercontent.com/61565464/129487913-2f19d5bc-82f1-4ca2-9778-d4a6d43803d2.MOV

**Comment by pserb** [comment]
Add a `max-width: 100%;` to your ad image classes (`class="Component-img-0-2-48"`)

**Comment by AndySok** [comment]
fixed, pushing onto the production build right now
