### ISSUE TITLE
upgrade to react16

### ISSUE THREAD

**Issue by jsonkao** [stuyspec/stuyspec.com#90]
Important things to note:
- In React 15, DOM elements could only return components or null. In React 16, we can also return strings and arrays (fragments). 
  - Arrays can be used in `SidebarContent` and others. If using arrays, look into `React.Fragment` component.
- It is possible to load React components outside of the DOM Tree in things called portals: `React.createPortal`.
  - This can be used for snackbar notifications, modals that call for subscription on page load, tooltips, etc.
  - Then we don't have to worry about `z-index` on these pop-ups/modals/etc.
- New component lifecycle method: `componentDidCatch(error) => { ... }`
  - In React 15, an error will break the whole DOM branch and you are forced to refresh the page. In React 16, React will just unmount the entire component tree and you are left with a blank page. If you use a `componentDidCatch` in a problematic component, the rest of the component tree will stay intact. The error will not propagate up the tree.
  - This let's us handle and display (or hide) the error and keep our app in a working state.

**Comment by DJankauskas** [comment]
This was done quite a while ago, but error catching was never implemented. I'll open a new issue for that.
