### ISSUE TITLE
articleBySlug loads in ArticlePage, then disappears from data props

### ISSUE THREAD

**Issue by jsonkao** [stuyspec/stuyspec.com#92]
## Note: this issue is on the `feature/apollo` branch.

Loading an article page will successfully send a GraphQL query, which then gives back `this.props.data` that contains an `articleBySlug`. However, the props are reloaded soon after and `articleBySlug` is removed from `data`. 

This is usually not be problematic—if the data was once there, then the errors that not having an `articleBySlug` brings will not unmount the article page. Here are the first few lines of the article page component:
```
if (data.loading) {
  return null;
}
data = humps.camelizeKeys(data);
const { articleBySlug } = data;
const { section } = articleBySlug;
```
As you can see, since there is no articleBySlug, the main error comes from the last line: `Cannot read property 'section' of undefined`.

This error heavily affects the comment-creating process.
1. After signing in in the modal, a `SIGN_IN_FULFILLED` action fills the accounts slice of the state with the user's session info (access-token, client, etc.) However, a `SIGN_IN_REJECTED` follows with the `Cannot read property 'section' of undefined` error. Thus, the accounts state has both the session and error text.
2. Despite this nuisance, the accounts state still has a session, and the CommentForm will allow me to post a comment. So I post one. Same thing: a `CREATE_COMMENT_FULFILLED` action fills the comments slice of the state with a success message. However, that is soon overridden by a `CREATE_COMMENT_REJECTED` that carries with it `Cannot read property 'section' of undefined.`

## What I've Done
1. I've tried using `componentWillUpdate` to store the articleBySlug into the local state of the article  page, setting `null` as the default article value. Same thing, but with null: `Cannot read property 'section' of null`.
2. I added a `shouldComponentUpdate` to protect this article value from bad new `data`'s. This fixes the initial error cry of the article page when it loads. However, after logging each props change, `data` seemingly has lost its `articleBySlug` even after my `shouldComponentUpdate` come sign-in time, subsequently messing with the comment-creating process again.

## How to Reproduce
Seed the Rails API with the latest `seeds.rb`. Load any article on CFA. You'll see that the console already has a `Cannot read property 'section' of undefined` error. Focus the comment text area and sign in with
```
email: john1@gmail.com
password: topsecret1
```
Despite the `SIGN_IN_REJECTED`, you have signed in, and the CommentForm should display your name and an optional log out button. Post a comment. A `CREATE_COMMENT_FULFILLED` action fills the comments slice of the state with a success message. However, that is soon overridden by a `CREATE_COMMENT_REJECTED` that carries with it `Cannot read property 'section' of undefined.`

The comment is actually created. However, it will not appear on the CommentThread until the page is reloaded because of the error message that the reject action put into the state.

_Also, for some reason, the create comment reject message will not appear on `:8080` (`gulp`) but appears on `:3002` (`gulp dev` and `node app --dev`)._

**Comment by DJankauskas** [comment]
This seems to have been a bug in old react-apollo versions. Migrating to newer features in a newer library function fixed the disappearing data; I've removed the article data saving hack.
