### ISSUE TITLE
replace constant DEVISE_EMAIL_CONFIRM_URL in gulpfile

### ISSUE THREAD

**Issue by jsonkao** [stuyspec/stuyspec.com#98]
The client app should be aware of its own URL. We can then send a `default_confirm_success_url` to the API whenever a new user is created. That way, account confirmation links in development will go to `localhost` and, in production, to `stuyspec.com`. 

## What we have now

In `stuy-spec-api/config/initializers/devise_token_auth.rb`, the confirm success url is set to our production link:
```rb
config.default_confirm_success_url = 'https://stuyspec.com'
```

If I create an account in `localhost` and click on the link in a mail catcher, the user is redirected to https://stuyspec.com; expected, but unwanted.

## Why put this behavior in the client app?

From the `devise_token_auth` documentation:
> By default [the `default_confirm_success_url`] value is expected to be sent by the client so that the API knows where to redirect users after successful email confirmation. If this param is set, the API will redirect to this value when no value is provided by the client.

**Comment by DJankauskas** [comment]
Gulpfile no longer used. May reopen this issue if local testing of user creation proves to be an issue.
